server:
  port: 2525
  servlet:
    context path: "/amenities-reservation/v1"

spring:
  mvc:
    path match:
      matching-strategy: ant-path-matcher
config:
  rest:
    service:
      addAmenityReservationUrl: http://localhost:5545/amenities-reservation/v1/reservation

app:
  name: spring boot application
  api:
    title: Spring Boot APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.abc.controller
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: true
